import traci
import sumolib
import math
import random
from collections import defaultdict
import sys
import matplotlib.pyplot as plt

SUMO_CFG = "city.sumocfg"
SIM_STEPS = 200
COMM_RANGE = 150

# Survivors (INSIDE MAP)
survivors = [(0, 0), (100, 50)]

MAX_ACTIVE_ALERTS = 5

def dist(a, b): return math.dist(a, b)

def log(x):
    print(x)
    sys.stdout.flush()

# ================= STORAGE =================
messages = {}
heard = defaultdict(set)
last_seen = {}
assigned = {}
rescued = set()

msg_id = 0

# ================= METRICS =================
total_alerts = 0
delivered_unique = set()
delays = []

# ================= ALERT =================
def create_alert(sender, pos):
    global msg_id, total_alerts

    mid = f"M{msg_id}"
    msg_id += 1
    total_alerts += 1

    messages[mid] = {
        "pos": pos,
        "time": traci.simulation.getTime(),
        "source": sender
    }

    last_seen[mid] = {
        "pos": pos,
        "time": traci.simulation.getTime()
    }

    heard[mid].add(sender)

    log(f"\n🚨 ALERT {mid} GENERATED by {sender}")
    return mid


# ================= MAIN =================
def main():

    sumo = sumolib.checkBinary("sumo-gui")
    traci.start([sumo, "-c", SUMO_CFG])

    try:
        while traci.simulation.getTime() < SIM_STEPS:

            traci.simulationStep()
            t = traci.simulation.getTime()

            vehicles = traci.vehicle.getIDList()
            positions = {v: traci.vehicle.getPosition(v) for v in vehicles}

            scouts = [v for v in vehicles if v.startswith("scout")]
            ambulances = [v for v in vehicles if v.startswith("amb")]

            log(f"\n====== TIME {int(t)} ======")
            log(f"Scouts: {scouts} | Ambulances: {ambulances}")

            # ================= DRAW SURVIVORS =================
            if t == 1:
                for i, s in enumerate(survivors):
                    try:
                        traci.poi.add(f"real_{i}", s[0], s[1], (255, 0, 0, 255))
                        traci.poi.setWidth(f"real_{i}", 20)
                        traci.poi.setHeight(f"real_{i}", 20)
                        log(f"Survivor at {s}")
                    except:
                        pass

            # ================= PASSIVE SENSING =================
            for v in scouts:
                for s in survivors:
                    if dist(positions[v], s) < 250:

                        traci.vehicle.setColor(v, (0,255,0))

                        sensor_type = random.choice(["HEAT", "SOUND", "VIBRATION"])

                        # LOGS
                        if sensor_type == "HEAT":
                            log(f"PASSIVE SENSOR: {v} detected HEAT near {s}")
                        elif sensor_type == "SOUND":
                            log(f"PASSIVE SENSOR: {v} detected SOUND")
                        else:
                            log(f"PASSIVE SENSOR: {v} detected VIBRATION")

                        mid = create_alert(v, s)

                        # UI SENSOR MARKER
                        poi_id = f"sensor_{mid}"

                        color_map = {
                            "HEAT": (255, 0, 0, 255),
                            "SOUND": (255, 255, 0, 255),
                            "VIBRATION": (128, 0, 128, 255)
                        }

                        try:
                            traci.poi.add(poi_id, s[0], s[1], color_map[sensor_type])
                            traci.poi.setWidth(poi_id, 15)
                            traci.poi.setHeight(poi_id, 15)
                        except:
                            pass

            # FORCE DEMO
            if int(t) == 80 and scouts:
                create_alert(scouts[0], survivors[0])

            # ================= COMMUNICATION =================
            for mid, info in messages.items():
                sender = info["source"]

                for v in vehicles:
                    if v in heard[mid]:
                        continue

                    if dist(info["pos"], positions[v]) < COMM_RANGE:
                        heard[mid].add(v)
                        log(f"{sender} ➜ {v} | {mid}")

            # ================= PREDICTION =================
            recent_msgs = list(last_seen.keys())[-MAX_ACTIVE_ALERTS:]
            predictions = {}

            for mid in recent_msgs:
                data = last_seen[mid]
                time_diff = t - data["time"]

                pred = (
                    data["pos"][0] + random.uniform(-2, 2) * time_diff,
                    data["pos"][1] + random.uniform(-2, 2) * time_diff
                )

                predictions[mid] = pred

                # 🔵 Prediction dot
                poi_id = f"pred_{mid}"

                if poi_id in traci.poi.getIDList():
                    traci.poi.setPosition(poi_id, pred[0], pred[1])
                else:
                    try:
                        traci.poi.add(poi_id, pred[0], pred[1], (0, 0, 255, 255))
                        traci.poi.setWidth(poi_id, 12)
                        traci.poi.setHeight(poi_id, 12)
                    except:
                        pass

                # ⚪ Last seen
                last_id = f"last_{mid}"
                try:
                    traci.poi.add(last_id, data["pos"][0], data["pos"][1], (255,255,255,255))
                    traci.poi.setWidth(last_id, 10)
                    traci.poi.setHeight(last_id, 10)
                except:
                    pass

                # 🟠 Heatmap zone
                size = 30
                poly_id = f"zone_{mid}"

                shape = [
                    (pred[0]-size, pred[1]-size),
                    (pred[0]+size, pred[1]-size),
                    (pred[0]+size, pred[1]+size),
                    (pred[0]-size, pred[1]+size)
                ]

                try:
                    traci.polygon.add(poly_id, shape, (255, 165, 0, 80), fill=True)
                except:
                    traci.polygon.setShape(poly_id, shape)

            # CLEAN LOG
            if int(t) % 10 == 0:
                for mid in predictions:
                    log(f"LAST-SEEN: {mid} at {last_seen[mid]['pos']}")
                    log(f"PREDICTED: {mid} moving")

            # ================= DISPATCH =================
            for mid, pred in predictions.items():

                if mid in assigned:
                    continue

                if not ambulances:
                    continue

                nearest = min(ambulances, key=lambda a: dist(positions[a], pred))

                try:
                    edge = traci.simulation.convertRoad(pred[0], pred[1])[0]
                    traci.vehicle.changeTarget(nearest, edge)

                    assigned[mid] = nearest
                    delivered_unique.add(mid)

                    delay = t - messages[mid]["time"]
                    delays.append(delay)

                    log(f"DISPATCH: {nearest} → {mid}")

                except:
                    pass

            # ================= RESCUE =================
            for mid, amb in assigned.items():

                if mid in rescued:
                    continue

                amb_pos = positions.get(amb)
                target = messages[mid]["pos"]

                if amb_pos and dist(amb_pos, target) < 25:
                    traci.vehicle.setColor(amb, (0,255,0))
                    rescued.add(mid)
                    log(f"RESCUE SUCCESS: {amb} reached {mid}")

    finally:
        traci.close()

        # ================= METRICS =================
        log("\n========== METRICS ==========")

        delivery = len(delivered_unique)/total_alerts if total_alerts else 0
        avg_delay = sum(delays)/len(delays) if delays else 0

        precision = 1.0 if delivered_unique else 0
        recall = len(delivered_unique)/total_alerts if total_alerts else 0
        f1 = 2*precision*recall/(precision+recall) if (precision+recall) else 0

        log(f"Total Alerts     : {total_alerts}")
        log(f"Delivered        : {len(delivered_unique)}")
        log(f"Delivery Ratio   : {delivery:.2f}")
        log(f"Avg Delay (sec)  : {avg_delay:.2f}")
        log(f"Precision        : {precision:.2f}")
        log(f"Recall           : {recall:.2f}")
        log(f"F1 Score         : {f1:.2f}")
        log("================================")

        # ================= GRAPH =================
        metrics = ["Delivery", "Delay", "F1"]
        values = [delivery, avg_delay, f1]

        plt.figure()
        plt.bar(metrics, values)
        plt.title("System Performance")
        plt.savefig("final_graph.png")
        plt.show()

        log("\nGraph saved as final_graph.png")
        log("\nFINAL SYSTEM COMPLETE")


if __name__ == "__main__":
    main()