// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbwxxeqvbggofsnpqelv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdid3h4ZXF2Ymdnb2ZzbnBxZWx2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3ODU4ODYsImV4cCI6MjA3MTM2MTg4Nn0.y_I1EH4IjOTyyummLgb-b2p1u6w29T3fXg8xEgV7xHc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});